---
title: "IMPT_results"
output: html_notebook
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
#load packages
library(gsheet)
library(dplyr)
library(formattable)
library(magrittr)
library(tidyverse)
library(tidyr)
library(ggplot2)
library(tidyverse)
library(lessR)
library(plotly)
library(wesanderson)
library(PRISMAstatement)
library(psych)
library(shiny)
library(metafor)
library(forestplot)
library(meta)
library(readxl)
library(DiagrammeR)
library(data.table)
library(htmltools)
library(reactable)
```

# results

### forestplot
```{r forestplot, echo=FALSE}
prisma(29911, 90, 16548, 16548, 16199, 349, 297, 52, 52)
```

### Study Characteristics
```{r table 1, include=FALSE}
url <- 'https://docs.google.com/spreadsheets/d/1DE08OpdFC2eH8VwAV-xLmsFByGh2VvL0DRDjPLhyo9U/edit?usp=sharing'
dat <- gsheet2tbl(url)

dat_clean <- dat %>%
  filter(!is.na(author) & !author == "test" & !author == 0)
dat_clean$cohort <- paste(dat_clean$author, dat_clean$year, dat_clean$cohort_id, sep = "_")

#select variables
t <- select(dat, id, author, year, cohort_id, sample_size, sample_size_pre, sample_size_post, sample_size_fu, cohort_name,
              nationality, female_gender, age_m, age_sd, patient_group, minimum_pain_duration, pain_duration_months_m, 
              pain_duration_sd) %>%
  filter(!is.na(author) & !author == "test" & !author == 0)

#recode
t$cohort_id <- t$cohort_id %>% dplyr::recode("1" = "a", "2" = "b")

#merge mean and sd
as.character(t$age_sd)
as.character(t$age_m)
t$age_sd <- paste("(", t$age_sd, ")", sep = "")
t$age_m_sd <- paste(t$age_m, t$age_sd, sep = " ")
t$attrition_post <- round(100-((t$sample_size_post/t$sample_size_pre)*100), 2)
t$attrition_fu <- round(100-((t$sample_size_fu/t$sample_size_pre)*100), 2)
t$year <- paste("(", t$year, ")", sep="")
t$author_year_id <- paste(t$author, t$year, t$cohort_id, sep = " ")

#change column order
t_1 <- select(t, id, author_year_id, cohort_name, sample_size, sample_size_pre, 
              sample_size_post, sample_size_fu, attrition_post, attrition_fu, 
              nationality, female_gender, age_m_sd, age_m, age_sd, patient_group, 
              minimum_pain_duration, pain_duration_months_m, pain_duration_sd
              )

#change column names
t_1 <- t_1 %>% 
  dplyr::rename(
    "study sample size" = "sample_size",
    "cohort sample size (pre)" = "sample_size_pre",
    "cohort sample size (post)" = "sample_size_post",
    "cohort sample size (final follow-up)" = "sample_size_fu",
    "attrition rate post intervention" = "attrition_post",
    "attrition rate at final follow-up" = "attrition_fu",
    "% females" = "female_gender",
    "patient group" = "patient_group",
    "minimum pain duration" = "minimum_pain_duration",
    "mean pain duration in months" = "pain_duration_months_m",
    "mean age (sd)" = "age_m_sd",
    "cohort name" = "cohort_name",
    "author (year)" = "author_year_id"
    ) 

t_1 <- t_1 %>% arrange(`author (year)`)
    
```

```{r, echo=FALSE}
unit.scale = function(x) (x - min(x)) / (max(x) - min(x))

#t_1$`attrition rate post intervention`[is.na(t_1$`attrition rate post intervention`)] <- 1
#na.exclude(t_1$`attrition rate post intervention`) %>%
#proportion()

###t_1[is.na(t_1)] = ''

formattable(t_1, 
            align = c("l", "l", rep("r", NCOL(t_1) - 2)),
            list(`attrition rate post intervention` = color_bar("#FA614B66", unit.scale),
                 `id` = FALSE,
                 `n_west` = FALSE,
                 `age_m` = FALSE,
                 `age_sd` = FALSE)
)
```

```{r, echo=FALSE}
t_1 <- select(dat, author, year, cohort_id, cohort_name, sample_size, sample_size_pre, sample_size_post, sample_size_fu, 
              nationality, female_gender, age_m, age_sd, patient_group, minimum_pain_duration, pain_duration_months_m, 
              pain_duration_sd) %>%
  filter(!is.na(author) & !author == "test" & !author == 0)

t_2 <- select(dat, author, year, cohort_id, treatment_aim, treatment_modalities, healthcare_providers, in_out_patient, type_of_contact, group_size,
              mode_of_delivery_subinfo, setting, time_span, hours, minutes, tailoring, followup_sessions_provided, 
              followup_sessions_description, other_healthcare_providers, other_procedures) %>%
  filter(!is.na(author) & !author == "test" & !author == 0)

#recode cohort_id
t_1$cohort_id <- t_1$cohort_id %>% dplyr::recode("1" = "a", "2" = "b")
t_2$cohort_id <- t_2$cohort_id %>% dplyr::recode("1" = "a", "2" = "b")

#merge mean and sd
as.character(t_1$age_sd)
as.character(t_1$age_m)
t_1$age_sd <- paste("(", t_1$age_sd, ")", sep = "")
t_1$age_m_sd <- paste(t_1$age_m, t_1$age_sd, sep = " ")
t_1$year <- paste("(", t_1$year, ")", sep="")
t_1$author_year <- paste(t_1$author, t_2$year, sep = " ")
t_2$year <- paste("(", t_2$year, ")", sep="")
t_2$author_year <- paste(t_2$author, t_2$year, sep = " ")
t_1$author_year <- paste(t_1$author, t_1$year, sep = " ")


#calculate attrition

t_1$attrition_post <- round(100-((t_1$sample_size_post/t_1$sample_size_pre)*100), 2)
t_1$attrition_fu <- round(100-((t_1$sample_size_fu/t_1$sample_size_post)*100), 2)



#change column order
t1 <- select(t_1, author_year, cohort_id, cohort_name, sample_size, sample_size_pre, 
              sample_size_post, sample_size_fu, attrition_post, attrition_fu, 
              nationality, female_gender, age_m_sd, age_m, age_sd, patient_group, 
              minimum_pain_duration, pain_duration_months_m
             )

#change column names
t1 <- t1 %>% 
  dplyr::rename(
    "study sample size" = "sample_size",
    "cohort sample size (pre)" = "sample_size_pre",
    "cohort sample size (post)" = "sample_size_post",
    "cohort sample size (final follow-up)" = "sample_size_fu",
    "attrition rate post intervention" = "attrition_post",
    "attrition rate at final follow-up" = "attrition_fu",
    "% females" = "female_gender",
    "patient group" = "patient_group",
    "minimum pain duration" = "minimum_pain_duration",
    "mean pain duration in months" = "pain_duration_months_m",
    "mean age (sd)" = "age_m_sd",
    "cohort name" = "cohort_name",
    "author (year)" = "author_year"
  ) 

t1 <- t1 %>% arrange(`author (year)`)

sample_cols <- c("study sample size", "cohort sample size (pre)", "cohort sample size (post)",
                 "cohort sample size (final follow-up)", "attrition rate post intervention",
                 "attrition rate at final follow-up")

patient_cols <- c("% females", "patient group", "minimum pain duration",
                  "mean pain duration in months", "mean age (sd)"
                  )

#create table 1 with reactable
reactable(t1,
          columns = list(
            "author (year)" = colDef(minWidth = 105),
            cohort_id = colDef(maxWidth = 30, name = "ID"),
            "cohort name" = colDef(minWidth = 105),
            "study sample size" = colDef(format = colFormat(digits = 0))
          ),
          defaultColGroup = colGroup(headerClass = "header"),
          style = list(fontFamily = "Arial Narrow", fontSize = "14px"),
          columnGroups = list(
            colGroup(name = "sample size", columns = sample_cols),
            colGroup(name = "patient characteristics", columns = patient_cols)
          ),
          defaultColDef = colDef(
            header = function(value) gsub("_", " ", value, fixed = TRUE),
            cell = function(value) format(value),
            align = "left",
            minWidth = 70
            )
          )
          
#create t2 with reactable
#create unique variable for each treatment modality
t_2$ed <- 0  
t_2$ed[str_detect(t_2$treatment_modalities, "education")] <- 1

t_2$ex <- 0  
t_2$ex[str_detect(t_2$treatment_modalities, "exercise")] <- 1

t_2$ga <- 0  
t_2$ga[str_detect(t_2$treatment_modalities, "graded activity")] <- 1

t_2$ph <- 0  
t_2$ph[str_detect(t_2$treatment_modalities, "pharmacological treatment")] <- 1

t_2$wo <- 0  
t_2$wo[str_detect(t_2$treatment_modalities, "workplace advice")] <- 1

t_2$bt <- 0  
t_2$bt[str_detect(t_2$treatment_modalities, "(cognitive) behavioral therapy")] <- 1

t_2$pm <- 0  
t_2$pm[str_detect(t_2$treatment_modalities, "pain management skills")] <- 1

t_2$te <- 0  
t_2$te[str_detect(t_2$treatment_modalities, "team meetings")] <- 1

t_2$ba <- 0  
t_2$ba[str_detect(t_2$treatment_modalities, "body awareness therapy")] <- 1

t_2$re <- 0  
t_2$re[str_detect(t_2$treatment_modalities, "relaxation")] <- 1

#create unique variable for each hcp
t_2$phy <- 0  
t_2$phy[str_detect(t_2$healthcare_providers, "Physician")] <- 1

t_2$psy <- 0  
t_2$psy[str_detect(t_2$healthcare_providers, "psychologist")] <- 1

t_2$pt <- 0  
t_2$pt[str_detect(t_2$healthcare_providers, "physical therapist")] <- 1

t_2$ot <- 0  
t_2$ot[str_detect(t_2$healthcare_providers, "nurse")] <- 1

t_2$nur <- 0  
t_2$nur[str_detect(t_2$healthcare_providers, "nurse")] <- 1

t_2$swo <- 0  
t_2$swo[str_detect(t_2$healthcare_providers, "social worker")] <- 1




t2 <- select(t_2, author_year, cohort_id, ed, ex, ga, bt, re, pm, ph, ba, wo, te, other_procedures, phy, psy, pt, ot, nur, swo,
             other_healthcare_providers, in_out_patient, type_of_contact, group_size, mode_of_delivery_subinfo, setting, 
             time_span, hours, minutes, tailoring, followup_sessions_provided, followup_sessions_description)

procedure_cols <- c("ed", "ex", "ga", "bt", "re", "pm", "ph", "ba", "wo", "te", "other_procedures")
hcp_cols <- c("phy", "psy", "pt", "ot", "nur", "swo", "other_healthcare_providers")

reactable(t2,
          defaultSorted = "author_year",
          defaultSortOrder = "asc",
          defaultColGroup = colGroup(headerClass = "header"),
          style = list(fontFamily = "Arial Narrow", fontSize = "14px"),
          columnGroups = list(
            colGroup(name = "Treatment modalities", columns = procedure_cols),
            colGroup(name = "Healthcare providers", columns = hcp_cols)
            ),
          defaultColDef = colDef(
            header = function(value) gsub("_", " ", value, fixed = TRUE),
            cell = function(value) format(value, nsmall = 1),
            align = "left",
            minWidth = 70,
            headerStyle = list(background = "#f7f7f8")
            ),
          columns = list(
            author_year = colDef(minWidth = 105),
            other_procedures = colDef(minWidth = 200),
            other_healthcare_providers = colDef(minWidth = 110),
            followup_sessions_description = colDef(minWidth = 150),
            cohort_id = colDef(maxWidth = 30, name = "ID"),
            ed = colDef(maxWidth = 30, cell = function(value) {
              # Render as ✘ or ✓
              if (value == 0) "\u2718" else "\u2713"
              }, style = function(value){
                if (value == 0) {color <- '#ABB2B9'} else {color <- '#28B463'}
                list(background = color)
              }),
            ex = colDef(maxWidth = 30, cell = function(value) {
              # Render as ✘ or ✓
              if (value == 0) "\u2718" else "\u2713"
            }, style = function(value){
              if (value == 0) {color <- '#ABB2B9'} else {color <- '#28B463'}
              list(background = color)
              }),
            ga = colDef(maxWidth = 30, cell = function(value) {
              # Render as ✘ or ✓
              if (value == 0) "\u2718" else "\u2713"
            }, style = function(value){
              if (value == 0) {color <- '#ABB2B9'} else {color <- '#28B463'}
              list(background = color)
            }),
            ph = colDef(maxWidth = 30, cell = function(value) {
              # Render as ✘ or ✓
              if (value == 0) "\u2718" else "\u2713"
            }, style = function(value){
              if (value == 0) {color <- '#ABB2B9'} else {color <- '#28B463'}
              list(background = color)
            }),
            wo = colDef(maxWidth = 30, cell = function(value) {
              # Render as ✘ or ✓
              if (value == 0) "\u2718" else "\u2713"
            }, style = function(value){
              if (value == 0) {color <- '#ABB2B9'} else {color <- '#28B463'}
              list(background = color)
            }),
            bt = colDef(maxWidth = 30, cell = function(value) {
              # Render as ✘ or ✓
              if (value == 0) "\u2718" else "\u2713"
            }, style = function(value){
              if (value == 0) {color <- '#ABB2B9'} else {color <- '#28B463'}
              list(background = color)
            }),
            pm = colDef(maxWidth = 30, cell = function(value) {
              # Render as ✘ or ✓
              if (value == 0) "\u2718" else "\u2713"
            }, style = function(value){
              if (value == 0) {color <- '#ABB2B9'} else {color <- '#28B463'}
              list(background = color)
            }),
            ba = colDef(maxWidth = 30, cell = function(value) {
              # Render as ✘ or ✓
              if (value == 0) "\u2718" else "\u2713"
            }, style = function(value){
              if (value == 0) {color <- '#ABB2B9'} else {color <- '#28B463'}
              list(background = color)
            }),
            te = colDef(maxWidth = 30, cell = function(value) {
              # Render as ✘ or ✓
              if (value == 0) "\u2718" else "\u2713"
            }, style = function(value){
              if (value == 0) {color <- '#ABB2B9'} else {color <- '#28B463'}
              list(background = color)
            }),
            re = colDef(maxWidth = 30, cell = function(value) {
              # Render as ✘ or ✓
              if (value == 0) "\u2718" else "\u2713"
            }, style = function(value){
              if (value == 0) {color <- '#ABB2B9'} else {color <- '#28B463'}
              list(background = color)
            }),
            phy = colDef(maxWidth = 30, cell = function(value) {
              # Render as ✘ or ✓
              if (value == 0) "\u2718" else "\u2713"
            }, style = function(value){
              if (value == 0) {color <- '#ABB2B9'} else {color <- '#28B463'}
              list(background = color)
            }),
            psy = colDef(maxWidth = 30, cell = function(value) {
              # Render as ✘ or ✓
              if (value == 0) "\u2718" else "\u2713"
            }, style = function(value){
              if (value == 0) {color <- '#ABB2B9'} else {color <- '#28B463'}
              list(background = color)
            }),
            pt = colDef(maxWidth = 30, cell = function(value) {
              # Render as ✘ or ✓
              if (value == 0) "\u2718" else "\u2713"
            }, style = function(value){
              if (value == 0) {color <- '#ABB2B9'} else {color <- '#28B463'}
              list(background = color)
            }),
            ot = colDef(maxWidth = 30, cell = function(value) {
              # Render as ✘ or ✓
              if (value == 0) "\u2718" else "\u2713"
            }, style = function(value){
              if (value == 0) {color <- '#ABB2B9'} else {color <- '#28B463'}
              list(background = color)
            }),
            nur = colDef(maxWidth = 30, cell = function(value) {
              # Render as ✘ or ✓
              if (value == 0) "\u2718" else "\u2713"
            }, style = function(value){
              if (value == 0) {color <- '#ABB2B9'} else {color <- '#28B463'}
              list(background = color)
            }),
            swo = colDef(maxWidth = 30, cell = function(value) {
              # Render as ✘ or ✓
              if (value == 0) "\u2718" else "\u2713"
            }, style = function(value){
              if (value == 0) {color <- '#ABB2B9'} else {color <- '#28B463'}
              list(background = color)
            })
          ),
          bordered = FALSE,
          highlight = FALSE,
          striped = FALSE,
          searchable = TRUE,
          showPageSizeOptions = TRUE,
          onClick = "expand"
          )
```




```{r, table 2 intervention characteristics, include=FALSE}

t_2 <- select(dat, author, year, treatment_aim, treatment_modalities, healthcare_providers, in_out_patient, type_of_contact, group_size,
              mode_of_delivery_subinfo, setting, time_span, hours, minutes, tailoring, followup_sessions_provided, 
              followup_sessions_description) %>%
  filter(!is.na(author) & !author == "test" & !author == 0)

#create variable author (year)
t_2$year <- paste("(", t$year, ")", sep="")
t_2$author_year_id <- paste(t$author, t$year, t$cohort_id, sep = " ")


#create variable type of treatment
t_2$type_of_contact <- dplyr::recode(t_2$type_of_contact, 
                            "Group (>90%)" = "Group",
                            "Individual (>90%)" = "Individual")

t_2$group_size <- ifelse(!is.na(t_2$group_size), 
                         paste(" (", t_2$group_size, ")", sep = ""),
                        NA
)

is.na(t_2$group_size)

t_2$group_size <- replace_na(t_2$group_size, "")
t_2$group <- paste(t_2$type_of_contact, t_2$group_size, sep = "")

t_2$`type of treatment` <- paste(t_2$in_out_patient, t_2$group, t_2$mode_of_delivery_subinfo, t_2$setting, 
                                 sep = "<br>")

#create variable treatment time
t_2$hrs <- ifelse(!is.na(t_2$hours), 
                         paste(t_2$hours, "h", sep = ""),
                        NA
)

t_2$min <- ifelse(!is.na(t_2$minutes), 
                         paste(t_2$minutes, "m", sep = ""),
                        NA
)

t_2$min <- replace_na(t_2$minutes, "")

t_2$duration <- ifelse(!is.na(t_2$hrs),
                       paste(t_2$hrs, t_2$min, sep=""),
                       NA
)

#create formatter table
t2 <- select(t_2, author_year_id, treatment_aim, treatment_modalities, healthcare_providers, `type of treatment`, 
             followup_sessions_description, time_span, duration, tailoring)


t2 <- t2 %>% 
  dplyr::rename(
    "author (year)" = "author_year_id",
    "treatment aim" = "treatment_aim",
    "treatment modalities" = "treatment_modalities",
    "healthcare providers" = "healthcare_providers",
    "follow-up sessions" = "followup_sessions_description",
    "time span (weeks)" = "time_span"
    )

t2 <- t2 %>% arrange(`author (year)`)
```

```{r, table 2 descriptive data analysis, include=FALSE}

#obtain descriptives of the sample sizes at various timepoints
qqnorm(t_2$time_span)
qqline(t_2$time_span)
qqnorm(t_2$hours)
qqline(t_2$hours)

describe(t_2)
#conclusion: time span is not normally distributed, so use median and range. hours is normally distributed, so use mean (sd)

table(t_2$in_out_patient)
table(t_2$type_of_contact)
table(t_2$tailoring)

is.na(t_2$tailoring)

#calculate proportion of the sample from non-western studies
#for each additional non-western study, add the id below to update the calculation

t_1$n_west <- if_else(t_1$id == 1 | t_1$id == 185 | t_1$id == 144, 1, 0)

#sum of all non-western sample sizes divided by the total sample size * 100
100 - (t_1$`cohort sample size (pre)` %>% subset(t_1$n_west == 1) %>%
  sum() / (sum(t_1$`cohort sample size (pre)`, na.rm = TRUE)) * 100)
```

```{r, echo=FALSE}
formattable(t2, 
            align = c("l", rep("l", NCOL(t2) - 1))
            )
```


```{r, include=FALSE}
describe(t_2)
```

ShinyApp forest plots
```{r}
## reverse scoring procedure ##
data <- read_excel("input/20200123.r_data_forest_plot.xlsx")
# return: new dataframe with corrected stds and means.
correct_rev_score <- function(data) {
  # Create new copy of data
  rev_corrected_data <- data.frame(data)
  
  # Iterate over each row in data
  for (row in 1:nrow(data)) {
    if (data[row, "rev_scoring"] == 1) {
      # Replace pre by post
      rev_corrected_data[row, "m_pre"] <- data[row, "m_post"]
      rev_corrected_data[row, "sd_pre"] <- data[row, "sd_post"]
      rev_corrected_data[row, "n_pre"] <- data[row, "n_post"]
      
      # Replace post by pre
      rev_corrected_data[row, "m_post"] <- data[row, "m_pre"]
      rev_corrected_data[row, "sd_post"] <- data[row, "sd_pre"]
      rev_corrected_data[row, "n_post"] <- data[row, "n_pre"]
    }
  }
  return(rev_corrected_data)
}
corrected_data <- correct_rev_score(data)

## create shinyapp ##

#step1: create tibble for corrected data
data_fp <- as_tibble(corrected_data)

#step 2: create Shinyapp
ui <- fluidPage(
  
  # App title ----
  headerPanel("Forest plot systematic review"),
  
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      
      # Input: Slider for the number of bins ----
      sliderInput(inputId = "r_value",
                  label = "R Correction Value:",
                  min = 0,
                  max = 1,
                  value = 0,
                  step = 0.1),
      
      selectInput(inputId = "outcome",
                  label = "select ouctome:",
                  choices = c("hr quality of life", "physical function", "pain interference", "depression", "anxiety",   
                              "self-efficacy", "social functioning", "pain intensity"),
                  selected = "pain interference"),
      
      selectInput(inputId = "contrast",
                  label = "select contrast:",
                  choices = c("pre-post", "post-fu", "pre-fu"),
                  selected = "pre-post")
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      plotOutput("forestplot")
      
    )
  )
)
# Define server logic required to draw a histogram ----
server <- function(input, output, session) {
  
  
  output$forestplot <- renderPlot({
    
    data_fp$ri <- input$r_value
    data_fp_meta <- escalc(measure="SMCR", m1i=m_post, m2i=m_pre, sd1i=sd_pre, ni=n_post, ri=ri, data=data_fp)
    fp_meta <- metafor::summary.escalc(data_fp_meta)
    fp_meta2 <- filter(fp_meta, contrast == input$contrast & outcome == input$outcome)
    fp_meta2$tabletext <- cbind(fp_meta2$author, fp_meta2$year, fp_meta2$n_pre, fp_meta2$measure, 
                                fp_meta2$fu_month)
    
    forestplot(fp_meta2$tabletext, fp_meta2$yi, fp_meta2$ci.lb, fp_meta2$ci.ub,
               zero = 0,
               cex = 2,
               lineheight = "auto",
               xlab = "SMD",
               lwd.ci= 3,
               col = fpColors(text="black", lines="#4393C3", box="#2166AC"),
               boxsize = .25
    )
  })
  
}

shinyApp(ui=ui, server=server)
```

time series anxiety
```{r}
dat_anx <- dat_clean %>%
    filter(measurements_anxiety == "Yes")  
  
  ts_m <- select (dat_anx, cohort, author, year, cohort_id, anx_pre_m, anx_post_m, anx_fu1_m,
                  anx_fu2_m, anx_fu3_m, measurements_anxiety, anx_name_measurement_instrument) %>%
    rename(instrument_name = anx_name_measurement_instrument, 
           pre_m = anx_pre_m,
           post_m = anx_post_m,
           fu1_m = anx_fu1_m,
           fu2_m = anx_fu2_m,
           fu3_m = anx_fu3_m,
           instrument_present = measurements_anxiety)
  
  ts_sd <- select (dat_anx, cohort, anx_pre_sd, anx_post_sd, anx_fu1_sd,
                   anx_fu2_sd, anx_fu3_sd) %>%
    rename( pre_sd = anx_pre_sd,
            post_sd = anx_post_sd,
            fu1_sd = anx_fu1_sd,
            fu2_sd = anx_fu2_sd,
            fu3_sd = anx_fu3_sd)
  
  ts_t <- select (dat_anx, cohort, anx_fu1_t, anx_fu2_t, anx_fu3_t) %>%
    rename( fu1_t = anx_fu1_t,
            fu2_t = anx_fu2_t,
            fu3_t = anx_fu3_t)
 

ts_t$pre_t = -20
ts_t$post_t = 0

#change SD columns to numeric
cols.num <- c("pre_sd","post_sd", "fu1_sd", "fu2_sd", "fu3_sd")
ts_sd[cols.num] <- sapply(ts_sd[cols.num],as.numeric)
#sapply(ts_sd, class)


#convert to long dataset
# The arguments to gather():
# - data: Data object
# - key: Name of new key column (made from names of data columns)
# - value: Name of new value column
# - ...: Names of source columns that contain values
# - factor_key: Treat the new key column as a factor (instead of character vector)
ts_m_long <- pivot_longer(ts_m, 
                          cols = c("pre_m", "post_m", "fu1_m", "fu2_m", "fu2_m", "fu3_m"),
                          names_to = "timepoint",
                          values_to = "m")

ts_sd_long <- pivot_longer(ts_sd, 
                           cols = c("pre_sd", "post_sd", "fu1_sd", "fu2_sd", "fu2_sd", "fu3_sd"),
                           names_to = "timepoint",
                           values_to = "sd")


ts_t_long <- pivot_longer(ts_t,
                          cols = c("pre_t", "post_t", "fu1_t", "fu2_t", "fu3_t"),
                          names_to = "timepoint",
                          values_to = "t")


#merge long datasets
ts_sd_long$timepoint <-  gsub("\\_sd*$","",ts_sd_long$timepoint)
ts_t_long$timepoint <- gsub("\\_t*$","",ts_t_long$timepoint)
ts_m_long$timepoint <- gsub("\\_m*$","",ts_m_long$timepoint)

ts_sdt_long <- merge(ts_sd_long, ts_t_long, c("cohort", "timepoint"))
ts_long <- merge(ts_sdt_long, ts_m_long, c("cohort", "timepoint"))

unique(ts_long$instrument_name)

#create max_score column

ts_long$max_scale = ts_long$instrument_name
ts_long$max_scale <- recode(ts_long$max_scale, "VAS" = 100,
                            "VAS (0-100)" = 100,
                            "PRI" = 78,
                            "MPI: pain severity" = 7,
                            "NRS" = 10,
                            "NPRS" = 10,
                            "NRS (0-10)" = 10,
                            "VAS (0-10)"= 10,
                            "NRS (0-100)" = 100,
                            "Likert pain intensity" = 6,
                            "RDQ" = 24,
                            "QBPDS" = 100,
                            "LBPRS" = 30,
                            "DRI" = 1200,
                            "DRI (0-100)" = 100, 
                            "MPI" = 6,
                            "ODI" = 100,
                            "ODI (0-1)" = 1,
                            "PDI" = 70,
                            "RMDQ" = 24,
                            "DPQ: Daily activities" = 100,
                            "SF-36 subscale Physical Functioning" = 100,
                            "NHP: PA" = 100,
                            "HFAQ" = 100,
                            "MPI: GA" = 6,
                            "Norfunk (0-3)" = 3,
                            "ADS (german scale of CES-D)" =60,
                            "HADS-D" =21,
                            "DASS" = 42,
                            "BDI-II" =63,
                            "Zung" =100,
                            "BDI" =63,
                            "depression index (DEPS)" =30,
                            "SCL90-D" = 52,
                            "HADS-A"= 21,
                            "VAS Anxiety (0-100)" = 100,
                            "SCL90-A" = 40,
                            "STAI" = 80
                            )

#create reverse scoring variable
#binary variable: do higher scores indicate better functioning? 0=no; 1=yes.
ts_long$rev_score = ts_long$instrument_name
ts_long$rev_score <- recode(ts_long$rev_score, "VAS" = 0,
                            "VAS (0-100)" = 0,
                            "PRI" = 0,
                            "MPI: pain severity" = 0,
                            "NRS" = 0,
                            "NPRS" = 0,
                            "NRS (0-10)" = 0,
                            "VAS (0-10)"= 0,
                            "NRS (0-100)" = 0,
                            "Likert pain intensity" = 0,
                            "RDQ" = 0,
                            "QBPDS" = 0,
                            "LBPRS" = 0,
                            "DRI" = 0,
                            "DRI (0-100)" = 0, 
                            "MPI" = 0,
                            "ODI" = 0,
                            "ODI (0-1)" = 0,
                            "PDI" = 0,
                            "RMDQ" = 0,
                            "DPQ: Daily activities" = 0,
                            "SF-36 subscale Physical Functioning" = 1,
                            "NHP: PA" = 0,
                            "HFAQ" = 1,
                            "MPI: GA" = 1,
                            "Norfunk (0-3)" = 1,
                            "ADS (german scale of CES-D)" =0,
                            "HADS-D" =0,
                            "DASS" =0,
                            "BDI-II" =0,
                            "Zung" =0,
                            "BDI" =0,
                            "depression index (DEPS)" =0,
                            "SCL90-D" =0,
                            "HADS-A"= 0,
                            "VAS Anxiety (0-100)" = 0,
                            "SCL90-A" = 0,
                            "STAI" = 0
                              )


#reverse scoring
ts_long$rev_score_m <- (ts_long$max_scale + 1)-ts_long$m 

#combining rev_score and normal score on contion of ts_long$rev_score

ts_long$m_final <- ts_long$m

for (row in 1:nrow(ts_long)) {
  if (ts_long[row, "rev_score"] == 0 & !is.na(ts_long[row, "rev_score"])) {
    # replace value by ts_long$rev_score_m
    ts_long[row, "m_final"] <- ts_long[row, "rev_score_m"]
  }
}


#standardize mean
ts_long$m_stand = (ts_long$m_final/ts_long$max_scale)*100



#create plot
p <- ggplot(ts_long, aes(x=t, y=m_stand, group=cohort, color=cohort, text = 
                           paste("Author: ", author,
                                 "<br>Year: ", year,
                                 "<br>Cohort ID: ", cohort_id,
                                 "<br>Instrument: ", instrument_name,
                                 "<br>Raw mean: ", m,
                                 "<br>Raw SD: ", sd,
                                 "<br>Standardized score ", m_stand
                           ))) +
  labs(y= "outcome standardized (0-100)") +
  geom_line(data=ts_long[!is.na(ts_long$m_stand),]) + 
  geom_point() +
  scale_x_continuous(name = "Time (months)",
                     breaks = c(-20, 0, 3, 6, 12, 24, 60, 120),
                     labels = c("pre", "post", "3m", "6m", "12m", "24m", "60m", "120m"),
                     limits = c(-20, 200))

ggplotly(p, tooltip = "text") %>%
  layout(
    xaxis = list(
      tickvals = c(-20, 0, 3, 6, 12, 24, 60, 120),
      ticktext = c("pre", "post", "3m", "6m", "12m", "24m", "60m", "120m"),
      ticklen = 5,
      tickwidth = 2,
      tickcolor = toRGB("blue"),
      range=c(-22, 26)
    ),
    yaxis = list(
      range=c(0, 100))
  ) 
```


time series self-efficacy
```{r}
dat_se <- dat_clean %>%
    filter(measurements_self_efficacy == "Yes")  
  
  ts_m <- select (dat_se, cohort, author, year, cohort_id, se_pre_m, se_post_m, se_fu1_m,
                  se_fu2_m, se_fu3_m, measurements_self_efficacy, se_name_measurement_instrument) %>%
    rename(instrument_name = se_name_measurement_instrument, 
           pre_m = se_pre_m,
           post_m = se_post_m,
           fu1_m = se_fu1_m,
           fu2_m = se_fu2_m,
           fu3_m = se_fu3_m,
           instrument_present = measurements_self_efficacy)
  
  ts_sd <- select (dat_se, cohort, se_pre_sd, se_post_sd, se_fu1_sd,
                   se_fu2_sd, se_fu3_sd) %>%
    rename( pre_sd = se_pre_sd,
            post_sd = se_post_sd,
            fu1_sd = se_fu1_sd,
            fu2_sd = se_fu2_sd,
            fu3_sd = se_fu3_sd)
  
  ts_t <- select (dat_se, cohort, se_fu1_t, se_fu2_t, se_fu3_t) %>%
    rename( fu1_t = se_fu1_t,
            fu2_t = se_fu2_t,
            fu3_t = se_fu3_t)


ts_t$pre_t = -20
ts_t$post_t = 0

#change SD columns to numeric
cols.num <- c("pre_sd","post_sd", "fu1_sd", "fu2_sd", "fu3_sd")
ts_sd[cols.num] <- sapply(ts_sd[cols.num],as.numeric)
#sapply(ts_sd, class)


#convert to long dataset
# The arguments to gather():
# - data: Data object
# - key: Name of new key column (made from names of data columns)
# - value: Name of new value column
# - ...: Names of source columns that contain values
# - factor_key: Treat the new key column as a factor (instead of character vector)
ts_m_long <- pivot_longer(ts_m, 
                          cols = c("pre_m", "post_m", "fu1_m", "fu2_m", "fu2_m", "fu3_m"),
                          names_to = "timepoint",
                          values_to = "m")

ts_sd_long <- pivot_longer(ts_sd, 
                           cols = c("pre_sd", "post_sd", "fu1_sd", "fu2_sd", "fu2_sd", "fu3_sd"),
                           names_to = "timepoint",
                           values_to = "sd")


ts_t_long <- pivot_longer(ts_t,
                          cols = c("pre_t", "post_t", "fu1_t", "fu2_t", "fu3_t"),
                          names_to = "timepoint",
                          values_to = "t")


#merge long datasets
ts_sd_long$timepoint <-  gsub("\\_sd*$","",ts_sd_long$timepoint)
ts_t_long$timepoint <- gsub("\\_t*$","",ts_t_long$timepoint)
ts_m_long$timepoint <- gsub("\\_m*$","",ts_m_long$timepoint)

ts_sdt_long <- merge(ts_sd_long, ts_t_long, c("cohort", "timepoint"))
ts_long <- merge(ts_sdt_long, ts_m_long, c("cohort", "timepoint"))

unique(ts_long$instrument_name)

#create max_score column

ts_long$max_scale = ts_long$instrument_name
ts_long$max_scale <- recode(ts_long$max_scale, "VAS" = 100,
                            "VAS (0-100)" = 100,
                            "PRI" = 78,
                            "MPI: pain severity" = 7,
                            "NRS" = 10,
                            "NPRS" = 10,
                            "NRS (0-10)" = 10,
                            "VAS (0-10)"= 10,
                            "NRS (0-100)" = 100,
                            "Likert pain intensity" = 6,
                            "RDQ" = 24,
                            "QBPDS" = 100,
                            "LBPRS" = 30,
                            "DRI" = 1200,
                            "DRI (0-100)" = 100, 
                            "MPI" = 6,
                            "ODI" = 100,
                            "ODI (0-1)" = 1,
                            "PDI" = 70,
                            "RMDQ" = 24,
                            "DPQ: Daily activities" = 100,
                            "SF-36 subscale Physical Functioning" = 100,
                            "NHP: PA" = 100,
                            "HFAQ" = 100,
                            "MPI: GA" = 6,
                            "Norfunk (0-3)" = 3,
                            "ADS (german scale of CES-D)" =60,
                            "HADS-D" =21,
                            "DASS" = 42,
                            "BDI-II" =63,
                            "Zung" =100,
                            "BDI" =63,
                            "depression index (DEPS)" =30,
                            "SCL90-D" = 52,
                            "HADS-A"= 21,
                            "VAS Anxiety (0-100)" = 100,
                            "SCL90-A" = 40,
                            "STAI" = 80,
                            "NHP: Emotional reactions" = 100,
                            "SF-36: mental health" = 100,
                            "DPQ: anxiety/depression" = 100,
                            "SCL-90: Hostility" = 24,
                            "PSEQ" = 60
                            )

#create reverse scoring variable
#binary variable: do higher scores indicate better functioning? 0=no; 1=yes.
ts_long$rev_score = ts_long$instrument_name
ts_long$rev_score <- recode(ts_long$rev_score, "VAS" = 0,
                            "VAS (0-100)" = 0,
                            "PRI" = 0,
                            "MPI: pain severity" = 0,
                            "NRS" = 0,
                            "NPRS" = 0,
                            "NRS (0-10)" = 0,
                            "VAS (0-10)"= 0,
                            "NRS (0-100)" = 0,
                            "Likert pain intensity" = 0,
                            "RDQ" = 0,
                            "QBPDS" = 0,
                            "LBPRS" = 0,
                            "DRI" = 0,
                            "DRI (0-100)" = 0, 
                            "MPI" = 0,
                            "ODI" = 0,
                            "ODI (0-1)" = 0,
                            "PDI" = 0,
                            "RMDQ" = 0,
                            "DPQ: Daily activities" = 0,
                            "SF-36 subscale Physical Functioning" = 1,
                            "NHP: PA" = 0,
                            "HFAQ" = 1,
                            "MPI: GA" = 1,
                            "Norfunk (0-3)" = 1,
                            "ADS (german scale of CES-D)" =0,
                            "HADS-D" =0,
                            "DASS" =0,
                            "BDI-II" =0,
                            "Zung" =0,
                            "BDI" =0,
                            "depression index (DEPS)" =0,
                            "SCL90-D" =0,
                            "HADS-A"= 0,
                            "VAS Anxiety (0-100)" = 0,
                            "SCL90-A" = 0,
                            "STAI" = 0,
                            "NHP: Emotional reactions" = 0,
                            "SF-36: mental health" = 1,
                            "DPQ: anxiety/depression" = 0,
                            "SCL-90: Hostility" = 0,
                            "PSEQ" = 1
                              )


#reverse scoring
ts_long$rev_score_m <- (ts_long$max_scale + 1)-ts_long$m 

#combining rev_score and normal score on contion of ts_long$rev_score

ts_long$m_final <- ts_long$m

for (row in 1:nrow(ts_long)) {
  if (ts_long[row, "rev_score"] == 0 & !is.na(ts_long[row, "rev_score"])) {
    # replace value by ts_long$rev_score_m
    ts_long[row, "m_final"] <- ts_long[row, "rev_score_m"]
  }
}


#standardize mean
ts_long$m_stand = (ts_long$m_final/ts_long$max_scale)*100



#create plot
p <- ggplot(ts_long, aes(x=t, y=m_stand, group=cohort, color=cohort, text = 
                           paste("Author: ", author,
                                 "<br>Year: ", year,
                                 "<br>Cohort ID: ", cohort_id,
                                 "<br>Instrument: ", instrument_name,
                                 "<br>Raw mean: ", m,
                                 "<br>Raw SD: ", sd,
                                 "<br>Standardized score ", m_stand
                           ))) +
  labs(y= "outcome standardized (0-100)") +
  geom_line(data=ts_long[!is.na(ts_long$m_stand),]) + 
  geom_point() +
  scale_x_continuous(name = "Time (months)",
                     breaks = c(-20, 0, 3, 6, 12, 24, 60, 120),
                     labels = c("pre", "post", "3m", "6m", "12m", "24m", "60m", "120m"),
                     limits = c(-20, 200))

ggplotly(p, tooltip = "text") %>%
  layout(
    xaxis = list(
      tickvals = c(-20, 0, 3, 6, 12, 24, 60, 120),
      ticktext = c("pre", "post", "3m", "6m", "12m", "24m", "60m", "120m"),
      ticklen = 5,
      tickwidth = 2,
      tickcolor = toRGB("blue"),
      range=c(-22, 26)
    ),
    yaxis = list(
      range=c(0, 100))
  ) 

```


#supplement: raw data extraction forms
```{r create data extraction forms, include=FALSE}
dat_ex <- dat %>%
  filter(!is.na(author) & !author == "test" & !author == 0)

dat_ex$cohort_id <- dat_ex$cohort_id %>% dplyr::recode("1" = "a", "2" = "b")

#create list of cohort ids
dat_ex$year2 <- paste("(", dat_ex$year, ")", sep="")
dat_ex$ayi <- paste(dat_ex$author, dat_ex$year2, dat_ex$cohort_id, sep = " ")

cohort_list <- (dat_ex$ayi) %>%
  as.data.frame() %>%
  unique() 

cohort_list <- arrange(cohort_list, .)



```

```{r, echo=FALSE}
#Shiny

ui <- fluidPage(
  
  # App title ----
  titlePanel("data extraction forms"),
  
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      
      # Input: Slider for the number of bins ----
      selectInput(inputId = "cohort",
                  label = "select cohort:",
                  choices = cohort_list,
                  selected = NULL)
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      formattableOutput(outputId = "data_extraction_table")
      
    )
  )
)

# Define server logic required to draw a histogram ----
server <- function(input, output, session) {
  
    output$data_extraction_table <- renderFormattable({
    
    extraction_data <- as.data.frame(t(dplyr::filter(dat_ex, ayi == input$cohort)))
    library(formattable)
    formattable(extraction_data)   
  
  })
  
}

shinyApp(ui, server)

```

